version: '3'
services:
  model_1:
    build:
      context: .
      dockerfile: Dockerfile
    image: multi-qa-mpnet-base-dot-v1
    container_name: multi-qa-mpnet-base-dot-v1
    ports:
      - "8000:8000"
    environment:
      - DOCKER_BUILDKIT=1